translations = {
    "en": {
        "login": "Login",
        "register": "Register",
        "logout": "Logout",
        "email": "Email",
        "password": "Password",
        "phone": "Phone",
        "role": "Role",
        "farmer": "Farmer",
        "kirana": "Kirana Store",
        "artisan": "Artisan",
        "have_account": "Already have an account?",
        "login_here": "Login here",
        "no_account": "Don't have an account?",
        "register_here": "Register here",
        "dashboard_title": "Product Dashboard",
        "add_product": "Add Product",
        "search_placeholder": "Search product...",
        "save": "Save",
        "cancel": "Cancel",
        "language": "Language",
        "read_instructions": "Read instructions",
        "chatbot_title": "Ask the Assistant",
        "ask_something": "Ask something",

    },
    "hi": {
        "login": "लॉग इन करें",
        "register": "पंजीकरण करें",
        "logout": "लॉग आउट",
        "email": "ईमेल",
        "password": "पासवर्ड",
        "phone": "फ़ोन",
        "role": "भूमिका",
        "farmer": "किसान",
        "kirana": "किराना स्टोर",
        "artisan": "कारीगर",
        "have_account": "पहले से खाता है?",
        "login_here": "यहां लॉगिन करें",
        "no_account": "खाता नहीं है?",
        "register_here": "यहां पंजीकरण करें",
        "dashboard_title": "उत्पाद डैशबोर्ड",
        "add_product": "उत्पाद जोड़ें",
        "search_placeholder": "उत्पाद खोजें...",
        "save": "सहेजें",
        "cancel": "रद्द करें",
        "language": "भाषा",
        "read_instructions": "निर्देश पढ़ें",
        "chatbot_title": "सहायक से पूछें",
        "ask_something": "कुछ पूछें",

    },
    "ta": {
        "login": "உள்நுழைய",
        "register": "பதிவுசெய்",
        "logout": "வெளியேறு",
        "email": "மின்னஞ்சல்",
        "password": "கடவுச்சொல்",
        "phone": "தொலைபேசி",
        "role": "பங்கு",
        "farmer": "விவசாயி",
        "kirana": "கிரானா கடை",
        "artisan": "கைவினையர்",
        "have_account": "ஏற்கனவே கணக்கு உள்ளதா?",
        "login_here": "இங்கே உள்நுழையவும்",
        "no_account": "கணக்கு இல்லையா?",
        "register_here": "இங்கே பதிவு செய்யவும்",
        "dashboard_title": "பொருள் டாஷ்போர்ட்",
        "add_product": "பொருளை சேர்க்க",
        "search_placeholder": "பொருள் தேடுங்கள்...",
        "save": "சேமிக்கவும்",
        "cancel": "ரத்து செய்யவும்",
        "language": "மொழி",
        "read_instructions": "விதிமுறைகளை வாசிக்கவும்",
        "chatbot_title": "உதவியாளரிடம் கேளுங்கள்",
        "chatbot_title": "உதவியாளரிடம் கேளுங்கள்",
        "ask_something": "ஏதேனும் கேளுங்கள்",

    }
}
